/*******************************************************************************
 * File Name: project.h
 * cydsfit No Version Information Found
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <WaveDAC8_1.h>
#include <WaveDAC_clk.h>
#include <WaveDAC_out_aliases.h>
#include <WaveDAC_out.h>
#include <Bootloadable_1.h>
#include <TFTSHIELD_1.h>
#include <SPIS_1.h>
#include <SPIS_1_PVT.h>
#include <Clock_1.h>
#include <miso_lcd_aliases.h>
#include <miso_lcd.h>
#include <mosi_aliases.h>
#include <mosi.h>
#include <sclk_aliases.h>
#include <sclk.h>
#include <miso_aliases.h>
#include <miso.h>
#include <mosi_lcd_aliases.h>
#include <mosi_lcd.h>
#include <sclk_lcd_aliases.h>
#include <sclk_lcd.h>
#include <ss_lcd_aliases.h>
#include <ss_lcd.h>
#include <cs_lcd_aliases.h>
#include <cs_lcd.h>
#include <dc_lcd_aliases.h>
#include <dc_lcd.h>
#include <rt_cs_aliases.h>
#include <rt_cs.h>
#include <WaveDAC8_1_Wave1_DMA_dma.h>
#include <WaveDAC8_1_Wave2_DMA_dma.h>
#include <WaveDAC8_1_VDAC8.h>
#include <WaveDAC8_1_BuffAmp.h>
#include <TFTSHIELD_1_SPIM_1.h>
#include <TFTSHIELD_1_SPIM_1_PVT.h>
#include <TFTSHIELD_1_CR_1.h>
#include <SPIS_1_IntClock.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

